name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  actions: read
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}
      
      - name: Environment Info
        run: |
          node --version
          npm --version
          npx nx --version
          git rev-parse HEAD
          git status
          pwd
      
      - name: Check Nx Configuration
        run: cat nx.json
      
      - name: Check Prisma Schema
        run: cat apps/todo-server/prisma/schema.prisma
      
      - name: Generate Prisma Client
        run: npx nx run todo-server:prisma-generate
      
      - name: Check Prisma Client
        run: ls -R apps/todo-server/node_modules/.prisma
      
      - name: Check Prisma Version
        run: npx prisma --version
      
      - name: List Affected Files
        run: npx nx print-affected --select=projects
      
      - name: TypeScript Check
        run: npx tsc --noEmit
      
      - run: npx nx format:write
      - run: npx nx format:check --verbose
      
      - run: npx nx affected -t lint test build
